version: "3"
services:
  app:
    build: "."
    container_name: "gae-py3-datastore"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - "./app:/app"
    command: sh -c "./build.sh"
